project_name: teamtalk_bot
before:
  hooks:
    - go mod tidy
builds:
  -
    env:
      - CGO_ENABLED=0
    binary: teamtalk_bot
    flags:
      - -trimpath
    ldflags:
      - -w -s -X main.Version={{.Version}} -X main.BuildTime={{.Env.DATE}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
archives:
  -
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
      arm64: aarch64
    format_overrides:
      - goos: windows
        format: zip
      - goos: darwin
        format: zip
    files:
      - LICENSE
      - README.MD
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
signs:
  - artifacts: checksum
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^release:'
source:
  enabled: true
  name_template: "{{ .ProjectName }}_source"
  format: "tar.gz"
